[site]
title = "Xuesong Li"
description = "PhD student at the Technical University of Munich."
favicon = "/icons/favicon.svg"
last_updated = "December 25, 2025"

[author]
name = "Xuesong Li"
title = "PhD Student"
institution = "Technical University of Munich"
avatar = "/icons/xuesong_icon.png"

[social]
# Contact information (leave blank or delete to hide)

email = "xuesong.li@tum.de"
location = "Munich, Germany"
location_url = "https://maps.app.goo.gl/SaiEwaeYTiH2qRgL8"
location_details = [
  "Boltzmannstra√üe 3, School of CIT",
  "Technical University of Munich, Munich, Germany"
]
google_scholar = "https://scholar.google.com/citations?user=ZEKz2ssAAAAJ&hl=en"
orcid = "https://orcid.org/0009-0000-2752-6334"
github = "https://github.com/noseefood"
linkedin = "https://www.linkedin.com/in/xuesong-li-robo/"

[features]
# Show a like button on the about page
enable_likes = true

# Display all subpages on a single page
enable_one_page_mode = false

[[navigation]]
title = "About"
type = "page"
target = "about"
href = "/"

[[navigation]]
title = "Publications"
type = "page"
target = "publications"
href = "/publications"

[[navigation]]
title = "Services"
type = "page"
target = "services"
href = "/services"

[[navigation]]
title = "CV"
type = "page"
target = "cv"
href = "/cv"
