[[news]]
date = "2025-08"
content = "Our work has been accepted by a prestigious journal (Medical Image Analysis) ðŸŽ‰"

[[news]]
date = "2025-06"
content = "Our work has been accepted by MICCAI 2025 ðŸŽ‰"
