type = "card"
title = "Services"
description = "Professional services and community involvement."

[[items]]
title = "Reviewer"
subtitle = "IROS 2023"
date = "2023"

[[items]]
title = "Reviewer"
subtitle = "RAL/IROS 2024/"
date = "2024"

[[items]]
title = "Reviewer"
subtitle = "TRO/TBME/TMRB/RAL/MICCAI 2025/"
date = "2025"
